#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ -d "client" ]; then
  ROOT_DIR="client"
else
  ROOT_DIR="."
fi

echo "🚀 Running pre-commit checks..."
(cd "$ROOT_DIR" && npx lint-staged)
(cd "$ROOT_DIR" && npm run type-check)
