#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Starting pre-commit checks..."

# Check if we are in the root and the client folder exists
if [ -d "client" ]; then
  echo "📂 Found client folder, running checks..."
  cd client && npx lint-staged
else
  # If we are already inside the client folder
  echo "📍 Already in client (or subfolder), running checks..."
  npx lint-staged
fi
